name: Go Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    if: startsWith(github.event.head_commit.message, 'build')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
          sudo apt install -y  libcurl4-openssl-dev libsystemd-dev  just meson ninja-build pkg-config libgtk-3-dev libdbus-1-dev curl libglib2.0-dev libsdbus-c++-dev nlohmann-json3-dev -m
          just
          just build-waylyrics
          TAG_NAME=$(date +"build-%Y%m%d-%H%M%S")
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          sha256sum ./waylyrics.so > waylyrics_sha256

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        prerelease: true
        name: ${{ env.TAG_NAME }}
        tag_name: ${{ env.TAG_NAME }}
        files: |
          waylyrics.so
          waylyrics_sha256
